Implement a Lobster like feature
xvw/muhokama pull request #64
Opened 2023-01-09 20:53 UTC by BastienDuplessier

:warning: Work in progress :warning: 

> Complete description will be coming soon

2023-01-12 13:22 UTC, gr-im commented
Some pre-nitpicking. 
- I suggest to put the creation form at the begining of the page
- I hope that we will have comments so I think that the feature is still Work In Progress. But I have no issue about merging (after review) a partial version of the feature so I suggest to remove the link in the header. WDYT ?

2023-01-12 13:35 UTC, gr-im requested changes
Except for the two suggestion I made early, it is very nice!
Congratulation, it is a very impressive first real contribution!

2023-01-13 05:03 UTC, aguillon commented on app/views/shared_link_views.ml
> +                ^ Templates.Util.format_date shared_link.creation_date
This prints "le 2023-01-13 06:48", and "le 2023-01-13 **à** 06:48" would be better. It's also true for topics and messages, so I think you can change it safely.

2023-01-13 05:17 UTC, aguillon approved these changes
Very nice, thank you.

It would be nice to have a way of discussing those links in the forum. What do you guys think of adding a shortcut button to create a topic about a link? We could also imagine that clicking the button makes you join an existing topic instead of creating a new one, if it already exists. This may require more stuff in the database though.

This should be added separately of course.

2023-01-16 23:05 UTC, gr-im approved these changes

2023-01-16 23:05 UTC, merged